# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b33230b8885b10d6ce078ce9b0fafcf9c18b9edebcf13c61f7a2e99f7ab65f57c154896e533b6e6bcd63f8812d27a7c7c8f79dd95faa611051922c7a208f9018

test:
  secret_key_base: 4e8a287b67509265c9dce1a36af64bcfe10814b8eaef36f8aa9a71c6fb9f98caf3d62d16c1814e98b60e2c7b60c36c8d97655ef911f922420f158dde9077076a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
